---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible
  roles:
    - role: common
      tags: common

- name: install and configure the web
  hosts: webservers 
  remote_user: ansible
  roles:
    - role: web
      tags: web

- name: install and configure the web
  hosts: webservers
  remote_user: ansible
  roles:
    - role: db 
      tags: db 

- name: install and configure the app 
  hosts: webservers
  remote_user: ansible
  vars_prompt:
    - name: "user_name"
      prompt: "Please Enter Your GitHub ID"
      private: no
    - name: "password"
      prompt: "Please Enter Your GitHub Password"
      private: yes 
  roles:
    - role: app 
      tags: app 
