---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible
  roles:
#    - { role: common, tags, common }
     - common

- name: install and configure the web
  hosts: webservers 
  remote_user: ansible
  roles:
#    - { role: web, tags: web}
     - web
