---

- name: memcachedユニットを登録します
  become: yes
  template:
    src: "{{ item.1.src | regex_replace('<listen_port>', item.0 ) }}"
    dest: "{{ item.1.dest | regex_replace('<listen_port>', item.0 ) }}"
    owner: root
    group: root
    mode: 0644
  with_nested:
    - ["11214"]
    - "{{ memcached_systemd_files  }}"

- name: memcachedを起動します
  become: yes
  systemd:
    name: memcached_11214.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: ms_securiteリポジトリをクローンします 
  become: yes
  git:
    repo: git@github.com:ms-securite/ms_securite.git
    dest: "/var/www/_dev.example.local"
    key_file: /home/ansible/.ssh/github
    accept_hostkey: yes
    update: no

- name: クローンディレクトリの権限を設定します
  become: yes
  file:
    dest: /var/www/_dev.example.local
    owner: root
    group: apache 
    mode: 0775
    recurse: yes

- name: appに必要なディレクトリを作成します
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: apache
    mode: 0775
  with_items:
    - /var/www/_dev.example.local/trunk/src/log
    - /var/www/_dev.example.local/trunk/src/app/cache
    - /var/www/_dev.example.local/trunk/src/mscache
    - /var/www/_dev.example.local/trunk/src/mscache/example
    - /var/www/_dev.example.local/trunk/src/mscache/fund
    - /var/www/_dev.example.local/trunk/src/mscache/store

- name: シンボリックファイルを作成します
  become: yes
  file:
    src: "/var/www/_dev.example.local/trunk/src"
    dest: "/var/www/dev.example.local"
    state: link
    owner: root
    group: apache
    mode: 0775

- name: バーチャルホスト設定ファイルを配置します
  become: yes
  copy:
    src: example.local/dev.example.local.conf
    dest: /etc/httpd/conf.d/dev.example.local.conf
    owner: root
    group: root
    mode: 0664
  notify: updated_httpd_config 

- name: バーチャルホストログディレクトリを作成します
  become: yes
  file:
    path: "{{ item }}" 
    state: directory
    owner: root
    group: root
    mode: 0775 
  with_items:
    - /etc/httpd/logs/dev.example.local:80
    - /etc/httpd/logs/dev.example.local:443

- name: 証明書の配置ディレクトリを作成します
  become: yes
  file:
    path: /etc/httpd/cert/example.local
    state: directory
    owner: root
    group: root
    mode: 0755
    
- name: サーバー証明書を配置します
  become: yes
  copy:
    src: "example.local/{{ item }}"
    dest: "/etc/httpd/cert/example.local/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - example.local.crt
    - example.local.key
  notify: updated_httpd_config 
