---
- name: install mysql repository
  become: yes
  yum:
    name: "{{ mysqld_5_7.repo_url }}"
    state: present
    validate_certs: yes

- name: install mysqld packages
  become: yes
  yum:
    name: "{{ item }}"
    enablerepo: "{{ mysqld_5_7.enable_repo }}" 
    state: present 
  with_items: "{{ mysqld_5_7.install_package }}"

- name: mkdir for mysql logs
  become: yes
  file:
    path: "{{ mysqld_5_7.mysql_log_dir }}"
    state: directory
    owner: mysql 
    group: mysql 
    mode: 0755
 
- name: running and enabled mysqld
  become: yes
  service:
    name: mysqld
    state: started
    enabled: yes 

- name: check .my.cnf exists
  stat:
    path: /home/ansible/.my.cnf
  register: root_profile

- name: get temporary password
  become: yes
  shell: |
    cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
  register: mysql_default_password
  when: not root_profile.stat.exists

- name: deploy init .my.cnf
  become: yes
  template:
    src: root.my.cnf.j2
    dest: /home/ansible/.my.cnf
    owner: ansible 
    group: ansible 
    mode: 0644
  when: not root_profile.stat.exists

- name: print tempolary key
  debug:
    msg: "{{ mysql_default_password.stdout }}"
  when: not root_profile.stat.exists

- name: change password validation to the easy way
  become: yes
  shell: |
    mysql -u root -p'{{ mysql_default_password.stdout }}' --connect-expired-password -e "SET GLOBAL validate_password_length=4;"
    mysql -u root -p'{{ mysql_default_password.stdout }}' --connect-expired-password -e "SET GLOBAL validate_password_policy=LOW;"
  when: not root_profile.stat.exists

- name: change root user password
  become: yes
  shell: |
    mysql -u root -p'{{ mysql_default_password.stdout }}' --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysqld_5_7.mysql_root_password}}';"
  when: not root_profile.stat.exists

- name: deploy changed.my.cnf
  become: yes
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: remove all anonymous user
  mysql_user:
    name: ''
    state: absent
    host: localhost

- name: create database
  mysql_db:
    name: ansible_test
    state: present
    encoding: utf8mb4

- name: create user
  mysql_user:
    name: "{{ item.name }}" 
    password: "{{ item.password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  with_items: "{{ mysqld_5_7.valid_users }}"

- name: import database
  mysql_db:
    state: import
    name: ms2
    target: /var/www/data/data_source/ms2.sql 

- name: restart mysqld
  become: yes
  service:
    name: mysqld
    state: restarted
