---
# build and install distcache-devel
- name: distcacheのソースファイルをダウンロード 
  become: yes
  get_url:
    url: "{{ distcache.url }}" 
    dest: "{{ apache_2_4.work_dir }}" 

- name: distcacheのパッケージ化
  become: yes
  shell: "rpmbuild --rebuild {{ distcache.src_filename }}"
  args: 
    chdir: "{{ apache_2_4.work_dir }}"
    creates: "{{ distcache.rpm_directory }}/{{ distcache.rpm_filenames.1 }}"

- name: distcacheパッケージ配置用ディレクトリ
  become: yes
  file:
    path: "{{ distcache.rpm_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: discacheのパッケージ配置
  become: yes
  shell: "find {{ apache_2_4.rpmbuild_dir }} -name '*.rpm' | xargs -i mv {} ."
  args:
    chdir: "{{ distcache.rpm_directory }}"
    creates: "{{ distcache.rpm_directory }}/{{ distcache.rpm_filenames.1 }}"

- name: distcache-develのインストール
  become: yes
  yum:
    name: "{{ distcache.rpm_directory }}/{{ item }}"
    state: present
  with_items: "{{ distcache.rpm_filenames }}" 
