---
# build and install php_5.6
- name: remiレポジトリのインストール
  become: yes
  yum:
   name: "{{ php_5_5.repo_url }}"
   state: present
- name: phpのインストール
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    disablerepo: "*"
    enablerepo: "{{ php_5_5.enable_repo }}"
  with_items: "{{ php_5_5.install_packages }}"
  notify: restart httpd

- name: php設定ファイル編集
  become: yes
  lineinfile:
    dest: "{{ item.file  }}"
    backrefs: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ php_5_5.config_changes }}"
  notify: restart httpd

- name: php用sampleファイル配置
  become: yes
  shell: "echo '<?php phpinfo(); ?>' > /var/www/html/info.php"
  args:
    creates: "/var/www/html/info.php" 
