---
# install httpd_2.4
- name: httpdをインストールをインストールします
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    disablerepo: "*"
    enablerepo: "ius,epel,base" 
  with_items:
    - httpd24u 

- name: extra-confのインクルードディレクトリを作成します
  become: yes
  file:
    path: "{{ httpd_2_4.extra_conf_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: virtualhost-confのインクルードディレクトリを作成します
  become: yes
  file:
    path: "{{ httpd_2_4.vhosts_conf_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: httpdの起動ユーザ・グループ設定します
  become: true
  lineinfile:
    dest: "{{ httpd_2_4.conf_file }}"
    backrefs: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^User.*"
      line: "User {{ httpd_2_4.user_name }}"
    - regexp: "^Group.*"
      line: "Group {{ httpd_2_4.group_name }}"
  notify: restart httpd

- name: httpdのサービス起動と自動起動を設定します
  become: yes
  service:
    name: httpd
    state: started
    enabled: yes
