---
# install httpd_2.4
- name: iusレポジトリをインストールします
  become: yes
  yum:
    name: "{{ httpd_2_4.repo_url }}"
    state: present

- name: httpdをインストールします
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    disablerepo: "*"
    enablerepo: "ius,epel,base" 
  with_items:
    - httpd24u 
    - httpd24u-mod_ssl 

- name: ディレクトを作成します
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/httpd/cert

- name: httpd.confを最適化します
  become: true
  lineinfile:
    dest: "{{ httpd_2_4.conf_file }}"
    backrefs: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^User.*"
      line: "User {{ httpd_2_4.user_name }}"
    - regexp: "^Group.*"
      line: "Group {{ httpd_2_4.group_name }}"
    - regexp: "^#ServerName.*$"
      line: "ServerName dev.example.local:80"
    - regexp: "^(DocumentRoot.*)$"
      line: "#\1"
  notify: restart httpd

- name: apacheグループにユーザを追加します
  become: yes
  user:
    name: "{{ item }}"
    groups: apache
    append: yes
  with_items:
    - vagrant
    - ansible

- name: httpdのサービス起動と自動起動を設定します
  become: yes
  service:
    name: httpd
    state: started
    enabled: yes
