---
- name: YUMレポジトリをインストールします 
  become: yes
  yum:
    name: "{{ item }}"
    state: present 
  with_items:
    - epel-release
    - "{{ php_5_6.repo_url }}" 
    - "{{ httpd_2_4.repo_url }}"
    - tree
    - yum-utils

- name: 追加レポジトリをデフォルト無効にします 
  become: yes
  shell: "yum-config-manager --disable ius epel remi-safe"
