---
- name: timezoneを設定します
  become: yes
  timezone:
    name: Asia/Tokyo

- name: YUMレポジトリをインストールします 
  become: yes
  yum:
    name: "{{ item }}"
    state: present 
  with_items:
    - epel-release
    - tree
    - yum-utils

- name: 追加レポジトリをデフォルト無効にします 
  become: yes
  shell: "yum-config-manager --disable ius epel remi-safe"

- name: memcachedをインストールします
  become: yes
  yum:
    name: memcached
    state: present
