---
- name: timezoneを設定します 
  become: yes
  timezone:
    name: Asia/Tokyo 

- name: selinuxを無効化します
  become: yes
  selinux:
    state: disabled

- name: hostsを設定します 
  become: yes
  lineinfile:
    dest: "/etc/hosts"
    backrefs: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ hosts_config }}"
