---
# vars file for web
httpd_2_4:
  # 起動ユーザ
  user_name: apache
  # 起動グループ
  group_name: apache
  # インストールリポジトリ
  repo_url: https://repo.ius.io/ius-release-el7.rpm
  # 設定ファイルパス
  conf_file: /etc/httpd/conf/httpd.conf

php_5_5:
  # php提供元レポジトリURL
  repo_url: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  # 利用レポジトリ
  enable_repo: remi-php55,remi-safe,epel,base
  # インストール対象パッケージ
  install_packages:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-opcache
    - php-xml
    - php-phalcon2
    - php-pecl-memcache
    - php-pecl-xdebug 
  # php設定ファイル変更箇所
  config_changes:
    - regexp: "^;(date.timezone) =.*"
      line: '\1 = Asia/Tokyo'
      file: "/etc/php.ini"
    - regexp: "^;(mbstring.language) =.*"
      line: '\1 = Japanese'
      file: "/etc/php.ini"
    - regexp: "^;(mbstring.internal_encoding) =.*"
      line: '\1 = UTF-8'
      file: "/etc/php.ini"
    - regexp: "^;(mbstring.http_input) =.*"
      line: '\1 = pass'
      file: "/etc/php.ini"
    - regexp: "^;(mbstring.http_output) =.*"
      line: '\1 = pass'
      file: "/etc/php.ini"
    - regexp: "^;(mbstring.encoding_translation) =.*"
      line: '\1 = off'
      file: "/etc/php.ini"
    - regexp: "^;(xdebug.remote_autostart) =.*"
      line: '\1 = 1'
      file: "/etc/php.d/xdebug.ini"
    - regexp: "^;(xdebug.remote_enable) =.*"
      line: '\1 = 1'
      file: "/etc/php.d/xdebug.ini"
    - regexp: "^;(xdebug.remote_host) =.*"
      line: '\1 = "localhost"'
      file: "/etc/php.d/xdebug.ini"
    - regexp: "^;(xdebug.remote_port) =.*"
      line: '\1 = 9001'
      file: "/etc/php.d/xdebug.ini"
